# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15r6zCheid2lJMfYrWX0l-3SkjCixLjSZ
"""

import streamlit as st
import joblib
import pandas as pd
import sklearn

# 1. Page Setup
st.set_page_config(page_title="Titanic Survival Predictor", page_icon="🚢")

st.title("🚢 Titanic Survival Predictor")
st.info(f"Current Scikit-Learn Version: {sklearn.__version__} (Needs 1.6.1)")

# 2. Load the Model Safely
@st.cache_resource
def load_model():
    try:
        # Note: Ensure the filename matches your uploaded file
        return joblib.load('trained_model (2).joblib')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.warning("Fix: Ensure your requirements.txt has 'scikit-learn==1.6.1'")
        return None

model = load_model()

if model:
    st.success("Model loaded successfully!")

    # 3. Create User Input Form
    with st.form("input_form"):
        col1, col2 = st.columns(2)

        with col1:
            pclass = st.selectbox("Passenger Class", [1, 2, 3], help="1=Wealthy, 3=Lower Class")
            sex = st.selectbox("Sex", ["male", "female"])
            age = st.slider("Age", 0, 100, 25)

        with col2:
            sibsp = st.number_input("Siblings/Spouses Aboard", 0, 10, 0)
            parch = st.number_input("Parents/Children Aboard", 0, 10, 0)
            fare = st.number_input("Fare Paid", 0.0, 600.0, 32.0)
            embarked = st.selectbox("Embarked From", ["S", "C", "Q"])

        submit = st.form_submit_button("Predict Survival")

    # 4. Prediction Logic
    if submit:
        # The DataFrame columns MUST match the order/names used during training
        input_df = pd.DataFrame({
            'Pclass': [pclass],
            'Sex': [sex],
            'Age': [age],
            'SibSp': [sibsp],
            'Parch': [parch],
            'Fare': [fare],
            'Embarked': [embarked]
        })

        try:
            prediction = model.predict(input_df)[0]
            probability = model.predict_proba(input_df)[0][1]

            st.divider()
            if prediction == 1:
                st.balloons()
                st.success(f"### Result: Survived! 🎉")
                st.write(f"Confidence: {probability:.2%}")
            else:
                st.error(f"### Result: Did not survive ⚰️")
                st.write(f"Survival Probability: {probability:.2%}")

        except Exception as e:
            st.error(f"Prediction Error: {e}")
            st.info("Tip: Double-check if your model expects these specific column names.")