# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQIkua_abwuO4lGX9at7JmSkivpyRP1E
"""

import streamlit as st
import joblib
import pandas as pd

# Page config
st.set_page_config(page_title="Titanic Predictor")

# Load model with error handling
@st.cache_resource
def load_my_model():
    try:
        return joblib.load('trained_model (1).joblib')
    except Exception as e:
        st.error(f"Failed to load model: {e}")
        st.info("Check if scikit-learn==1.6.1 is in your requirements.txt")
        return None

model = load_my_model()

st.title("Titanic Survival Prediction")

if model:
    # Form for inputs
    with st.form("user_inputs"):
        pclass = st.selectbox("Class", [1, 2, 3])
        sex = st.selectbox("Sex", ["male", "female"])
        age = st.number_input("Age", 0, 100, 25)
        sibsp = st.number_input("Siblings/Spouses", 0, 10, 0)
        parch = st.number_input("Parents/Children", 0, 10, 0)
        fare = st.number_input("Fare", 0.0, 500.0, 30.0)
        embarked = st.selectbox("Embarked", ["S", "C", "Q"])

        submitted = st.form_submit_button("Predict")

    if submitted:
        # Create a dataframe with the EXACT names used in training
        data = pd.DataFrame({
            'Pclass': [pclass],
            'Sex': [sex],
            'Age': [age],
            'SibSp': [sibsp],
            'Parch': [parch],
            'Fare': [fare],
            'Embarked': [embarked]
        })

        prediction = model.predict(data)

        if prediction[0] == 1:
            st.success("The passenger survived!")
        else:
            st.error("The passenger did not survive.")