# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3wus7KPHL1qcFqLvofh_MDMqlS4QpgR
"""

import streamlit as st
import joblib
import pandas as pd
import sklearn

st.set_page_config(page_title="Titanic Predictor")

# This helps us debug the version issue
st.sidebar.write(f"Running Scikit-Learn version: {sklearn.__version__}")

@st.cache_resource
def load_model():
    # Make sure this matches your filename exactly
    return joblib.load('trained_model (1).joblib')

try:
    model = load_model()
    st.success("Model loaded successfully!")
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop() # Stops the app here if the model fails to load

# --- Your Prediction UI Code follows ---
st.title("Titanic Survival Prediction")
pclass = st.selectbox("Ticket Class", [1, 2, 3])
sex = st.selectbox("Sex", ["male", "female"])
age = st.slider("Age", 0, 80, 25)
fare = st.number_input("Fare", value=32.0)

if st.button("Predict"):
    # Create input data - Names must match training exactly!
    features = pd.DataFrame([[pclass, sex, age, fare]],
                            columns=['Pclass', 'Sex', 'Age', 'Fare'])

    prediction = model.predict(features)
    if prediction[0] == 1:
        st.balloons()
        st.success("Result: Survived!")
    else:
        st.error("Result: Did not survive.")