# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-20-WMReSE6tY8V3ZlWC2HK7AzLmwc1
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# Set page title and icon
st.set_page_config(page_title="Titanic Survival Predictor", page_icon="🚢")

# 1. Load the trained model
@st.cache_resource
def load_model():
    try:
        return joblib.load('trained_model (1).joblib')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.info("Ensure scikit-learn is version 1.6.1 in your requirements.txt")
        return None

model = load_model()

# 2. User Interface
st.title("🚢 Titanic Survival Predictor")
st.markdown("""
This app predicts whether a passenger would have survived the Titanic disaster.
Fill in the details below to get a prediction.
""")

# Input fields
with st.form("prediction_form"):
    col1, col2 = st.columns(2)

    with col1:
        pclass = st.selectbox("Passenger Class", [1, 2, 3], help="1 = Upper, 2 = Middle, 3 = Lower")
        sex = st.selectbox("Sex", ["male", "female"])
        age = st.number_input("Age", min_value=0, max_value=100, value=30)
        sibsp = st.number_input("Siblings/Spouses Aboard", min_value=0, max_value=10, value=0)

    with col2:
        parch = st.number_input("Parents/Children Aboard", min_value=0, max_value=10, value=0)
        fare = st.number_input("Fare Paid", min_value=0.0, value=32.0)
        embarked = st.selectbox("Port of Embarkation", ["S", "C", "Q"],
                                help="S = Southampton, C = Cherbourg, Q = Queenstown")

    submit = st.form_submit_button("Predict Survival Status")

# 3. Prediction Logic
if submit and model:
    # Prepare the input data in the exact format the model expects
    # Note: Column names must match the training dataset exactly
    input_df = pd.DataFrame({
        'Pclass': [pclass],
        'Sex': [sex],
        'Age': [age],
        'SibSp': [sibsp],
        'Parch': [parch],
        'Fare': [fare],
        'Embarked': [embarked]
    })

    try:
        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0][1]

        st.divider()
        if prediction == 1:
            st.success(f"### Result: Passenger Survived! 🎉")
            st.metric("Survival Probability", f"{probability:.2%}")
        else:
            st.error(f"### Result: Passenger Did Not Survive ⚰️")
            st.metric("Survival Probability", f"{probability:.2%}")

    except Exception as e:
        st.error(f"Prediction Error: {e}")
        st.warning("This error usually happens if the column names in the code don't match the names used during training.")