# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifVkwceFOLtDrEP-FulhN0ZnbksTFrgt
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# 1. Load the trained model
model = joblib.load('trained_model.joblib')

# 2. Set up the UI
st.set_page_config(page_title="Titanic Survival Predictor")
st.title("🚢 Titanic Survival Predictor")
st.markdown("Enter the passenger details below to see if they would have survived the shipwreck.")

# 3. Create input fields for the user
# Note: Ensure these column names match exactly what your model was trained on
col1, col2 = st.columns(2)

with col1:
    pclass = st.selectbox("Passenger Class (1st = Wealthiest)", [1, 2, 3])
    sex = st.selectbox("Sex", ["male", "female"])
    age = st.slider("Age", 0, 100, 30)

with col2:
    sibsp = st.number_input("Siblings/Spouses Aboard", min_value=0, max_value=10, value=0)
    parch = st.number_input("Parents/Children Aboard", min_value=0, max_value=10, value=0)
    fare = st.number_input("Fare Paid", min_value=0.0, value=32.0)
    embarked = st.selectbox("Port of Embarkation", ["S", "C", "Q"])

# 4. Prediction Logic
if st.button("Predict Survival Status"):
    # Create a DataFrame for the input
    input_data = pd.DataFrame({
        'Pclass': [pclass],
        'Sex': [sex],
        'Age': [age],
        'SibSp': [sibsp],
        'Parch': [parch],
        'Fare': [fare],
        'Embarked': [embarked]
    })

    try:
        # Make prediction
        prediction = model.predict(input_data)
        probability = model.predict_proba(input_data)[0][1]

        st.divider()

        if prediction[0] == 1:
            st.success(f"### Result: Survived! 🎉")
            st.write(f"Survival Probability: {probability:.2%}")
        else:
            st.error(f"### Result: Did not survive ️⚰️")
            st.write(f"Survival Probability: {probability:.2%}")

    except Exception as e:
        st.error(f"Error: {e}")
        st.info("Check if your model expects specific column names or more features.")