# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hjR_Hr4EhkgRQbvu9DxlRKJIFcw-o8A
"""

import streamlit as st
import joblib
import pandas as pd
import sklearn

# 1. Page Configuration
st.set_page_config(page_title="Titanic Predictor", page_icon="🚢")
st.title("🚢 Titanic Survival Prediction")

# Show current version in the sidebar to confirm the fix worked
st.sidebar.write(f"**Environment Info:**")
st.sidebar.write(f"Scikit-Learn: {sklearn.__version__}")

# 2. Load Model Safely
@st.cache_resource
def load_model():
    try:
        # Note: Ensure this filename matches exactly what is in your folder
        return joblib.load('trained_model (2).joblib')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.info("Check your requirements.txt. You need scikit-learn==1.6.1")
        return None

model = load_model()

if model:
    # 3. User Inputs
    with st.form("input_form"):
        col1, col2 = st.columns(2)
        with col1:
            pclass = st.selectbox("Passenger Class", [1, 2, 3])
            sex = st.selectbox("Sex", ["male", "female"])
            age = st.number_input("Age", 0, 100, 25)
        with col2:
            sibsp = st.number_input("Siblings/Spouses", 0, 8, 0)
            parch = st.number_input("Parents/Children", 0, 6, 0)
            fare = st.number_input("Fare", 0.0, 500.0, 32.0)
            embarked = st.selectbox("Embarked", ["S", "C", "Q"])

        submitted = st.form_submit_button("Predict Result")

    # 4. Run Prediction
    if submitted:
        # Create input dataframe - Ensure column names match your training data
        input_data = pd.DataFrame({
            'Pclass': [pclass],
            'Sex': [sex],
            'Age': [age],
            'SibSp': [sibsp],
            'Parch': [parch],
            'Fare': [fare],
            'Embarked': [embarked]
        })

        prediction = model.predict(input_data)[0]
        prob = model.predict_proba(input_data)[0][1]

        st.divider()
        if prediction == 1:
            st.success(f"### Result: Passenger Survived! 🎉")
            st.write(f"Survival Probability: {prob:.2%}")
        else:
            st.error(f"### Result: Passenger Did Not Survive ⚰️")
            st.write(f"Survival Probability: {prob:.2%}")